/*
SQLyog  v12.2.6 (64 bit)
MySQL - 5.6.34 : Database - ofbizolap
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ofbizolap` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `ofbizolap`;

/*Table structure for table `currency_dimension` */

DROP TABLE IF EXISTS `currency_dimension`;

CREATE TABLE `currency_dimension` (
  `DIMENSION_ID` varchar(20) NOT NULL,
  `CURRENCY_ID` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`DIMENSION_ID`),
  KEY `CRRNC_DMNSN_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `CRRNC_DMNSN_TXCRTS` (`CREATED_TX_STAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `currency_dimension` */

insert  into `currency_dimension`(`DIMENSION_ID`,`CURRENCY_ID`,`DESCRIPTION`,`LAST_UPDATED_STAMP`,`LAST_UPDATED_TX_STAMP`,`CREATED_STAMP`,`CREATED_TX_STAMP`) values 
('_NA_',NULL,'Currency Not Set.','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52'),
('_NF_',NULL,'Currency Not Found.','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52');

/*Table structure for table `date_dimension` */

DROP TABLE IF EXISTS `date_dimension`;

CREATE TABLE `date_dimension` (
  `DIMENSION_ID` varchar(20) NOT NULL,
  `DATE_VALUE` date DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DAY_NAME` varchar(60) DEFAULT NULL,
  `DAY_OF_MONTH` decimal(20,0) DEFAULT NULL,
  `DAY_OF_YEAR` decimal(20,0) DEFAULT NULL,
  `MONTH_NAME` varchar(60) DEFAULT NULL,
  `MONTH_OF_YEAR` decimal(20,0) DEFAULT NULL,
  `YEAR_NAME` decimal(20,0) DEFAULT NULL,
  `WEEK_OF_MONTH` decimal(20,0) DEFAULT NULL,
  `WEEK_OF_YEAR` decimal(20,0) DEFAULT NULL,
  `YEAR_MONTH_DAY` varchar(60) DEFAULT NULL,
  `YEAR_AND_MONTH` varchar(60) DEFAULT NULL,
  `WEEKDAY_TYPE` varchar(60) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`DIMENSION_ID`),
  KEY `DT_DMNSN_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `DT_DMNSN_TXCRTS` (`CREATED_TX_STAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `date_dimension` */

insert  into `date_dimension`(`DIMENSION_ID`,`DATE_VALUE`,`DESCRIPTION`,`DAY_NAME`,`DAY_OF_MONTH`,`DAY_OF_YEAR`,`MONTH_NAME`,`MONTH_OF_YEAR`,`YEAR_NAME`,`WEEK_OF_MONTH`,`WEEK_OF_YEAR`,`YEAR_MONTH_DAY`,`YEAR_AND_MONTH`,`WEEKDAY_TYPE`,`LAST_UPDATED_STAMP`,`LAST_UPDATED_TX_STAMP`,`CREATED_STAMP`,`CREATED_TX_STAMP`) values 
('_NA_',NULL,'Date Not Set.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52'),
('_NF_',NULL,'Date Not Found.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52');

/*Table structure for table `inventory_item_fact` */

DROP TABLE IF EXISTS `inventory_item_fact`;

CREATE TABLE `inventory_item_fact` (
  `INVENTORY_ITEM_ID` varchar(20) NOT NULL,
  `FACILITY_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_DIM_ID` varchar(20) DEFAULT NULL,
  `ORIG_CURRENCY_DIM_ID` varchar(20) DEFAULT NULL,
  `INVENTORY_DATE_DIM_ID` varchar(20) DEFAULT NULL,
  `QUANTITY_ON_HAND_TOTAL` decimal(18,6) DEFAULT NULL,
  `AVAILABLE_TO_PROMISE_TOTAL` decimal(18,6) DEFAULT NULL,
  `UNIT_COST` decimal(18,6) DEFAULT NULL,
  `SOLDOUT_AMOUNT` decimal(18,6) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`INVENTORY_ITEM_ID`),
  KEY `IIF_INVPRODUCT` (`PRODUCT_DIM_ID`),
  KEY `IIF_INVCURRENCY` (`ORIG_CURRENCY_DIM_ID`),
  KEY `IIF_INVDATE` (`INVENTORY_DATE_DIM_ID`),
  KEY `INVR_ITM_FCT_TXSTP` (`LAST_UPDATED_TX_STAMP`),
  KEY `INVR_ITM_FCT_TXCRS` (`CREATED_TX_STAMP`),
  CONSTRAINT `IIF_INVCURRENCY` FOREIGN KEY (`ORIG_CURRENCY_DIM_ID`) REFERENCES `currency_dimension` (`DIMENSION_ID`),
  CONSTRAINT `IIF_INVDATE` FOREIGN KEY (`INVENTORY_DATE_DIM_ID`) REFERENCES `date_dimension` (`DIMENSION_ID`),
  CONSTRAINT `IIF_INVPRODUCT` FOREIGN KEY (`PRODUCT_DIM_ID`) REFERENCES `product_dimension` (`DIMENSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `inventory_item_fact` */

/*Table structure for table `product_dimension` */

DROP TABLE IF EXISTS `product_dimension`;

CREATE TABLE `product_dimension` (
  `DIMENSION_ID` varchar(20) NOT NULL,
  `PRODUCT_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_TYPE` varchar(255) DEFAULT NULL,
  `BRAND_NAME` varchar(100) DEFAULT NULL,
  `INTERNAL_NAME` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`DIMENSION_ID`),
  KEY `PRDCT_DMNSN_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `PRDCT_DMNSN_TXCRTS` (`CREATED_TX_STAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `product_dimension` */

insert  into `product_dimension`(`DIMENSION_ID`,`PRODUCT_ID`,`PRODUCT_TYPE`,`BRAND_NAME`,`INTERNAL_NAME`,`LAST_UPDATED_STAMP`,`LAST_UPDATED_TX_STAMP`,`CREATED_STAMP`,`CREATED_TX_STAMP`) values 
('_NA_',NULL,NULL,NULL,NULL,'2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52'),
('_NF_',NULL,NULL,NULL,NULL,'2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52','2017-02-16 18:48:52');

/*Table structure for table `sales_invoice_item_fact` */

DROP TABLE IF EXISTS `sales_invoice_item_fact`;

CREATE TABLE `sales_invoice_item_fact` (
  `INVOICE_ID` varchar(20) NOT NULL,
  `INVOICE_ITEM_SEQ_ID` varchar(20) NOT NULL,
  `ORDER_ID` varchar(20) DEFAULT NULL,
  `INVOICE_DATE_DIM_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_DIM_ID` varchar(20) DEFAULT NULL,
  `BILL_TO_CUSTOMER_DIM_ID` varchar(20) DEFAULT NULL,
  `ORIG_CURRENCY_DIM_ID` varchar(20) DEFAULT NULL,
  `QUANTITY` decimal(18,6) DEFAULT NULL,
  `EXT_GROSS_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_DISCOUNT_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_NET_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_TAX_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_MAN_FIXED_COST` decimal(18,3) DEFAULT NULL,
  `EXT_MAN_VAR_COST` decimal(18,3) DEFAULT NULL,
  `EXT_STORAGE_COST` decimal(18,3) DEFAULT NULL,
  `EXT_DISTRIBUTION_COST` decimal(18,3) DEFAULT NULL,
  `CONTRIBUTION_AMOUNT` decimal(18,3) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ID`,`INVOICE_ITEM_SEQ_ID`),
  KEY `SIIF_INVDATE` (`INVOICE_DATE_DIM_ID`),
  KEY `SIIF_CURRENCY` (`ORIG_CURRENCY_DIM_ID`),
  KEY `SIIF_PRODUCT` (`PRODUCT_DIM_ID`),
  KEY `SLS_INC_ITM_FCT_TP` (`LAST_UPDATED_TX_STAMP`),
  KEY `SLS_INC_ITM_FCT_TS` (`CREATED_TX_STAMP`),
  CONSTRAINT `SIIF_CURRENCY` FOREIGN KEY (`ORIG_CURRENCY_DIM_ID`) REFERENCES `currency_dimension` (`DIMENSION_ID`),
  CONSTRAINT `SIIF_INVDATE` FOREIGN KEY (`INVOICE_DATE_DIM_ID`) REFERENCES `date_dimension` (`DIMENSION_ID`),
  CONSTRAINT `SIIF_PRODUCT` FOREIGN KEY (`PRODUCT_DIM_ID`) REFERENCES `product_dimension` (`DIMENSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sales_invoice_item_fact` */

/*Table structure for table `sales_order_item_fact` */

DROP TABLE IF EXISTS `sales_order_item_fact`;

CREATE TABLE `sales_order_item_fact` (
  `ORDER_ID` varchar(20) NOT NULL,
  `ORDER_ITEM_SEQ_ID` varchar(20) NOT NULL,
  `ORDER_DATE_DIM_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_DIM_ID` varchar(20) DEFAULT NULL,
  `ORIG_CURRENCY_DIM_ID` varchar(20) DEFAULT NULL,
  `BILL_TO_CUSTOMER_DIM_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_CATEGORY_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_STORE_ID` varchar(20) DEFAULT NULL,
  `SALES_CHANNEL_ENUM_ID` varchar(20) DEFAULT NULL,
  `STATUS_ID` varchar(20) DEFAULT NULL,
  `BRAND` varchar(100) DEFAULT NULL,
  `POD` varchar(100) DEFAULT NULL,
  `ACCOUNT` varchar(100) DEFAULT NULL,
  `QUANTITY` decimal(18,6) DEFAULT NULL,
  `EXT_GROSS_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_GROSS_COST` decimal(18,3) DEFAULT NULL,
  `EXT_DISCOUNT_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_NET_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_SHIPPING_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_TAX_AMOUNT` decimal(18,3) DEFAULT NULL,
  `G_S` decimal(18,3) DEFAULT NULL,
  `G_M_S` decimal(18,3) DEFAULT NULL,
  `G_M_P` decimal(18,3) DEFAULT NULL,
  `G_S_S` decimal(18,3) DEFAULT NULL,
  `G_S_C` decimal(18,3) DEFAULT NULL,
  `G_S_P` decimal(18,3) DEFAULT NULL,
  `G_P` decimal(18,3) DEFAULT NULL,
  `COUNT_ORDER` decimal(18,6) DEFAULT NULL,
  `PRODUCT_PROMO_CODE` varchar(20) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`,`ORDER_ITEM_SEQ_ID`),
  KEY `SOIF_ORDERDATE` (`ORDER_DATE_DIM_ID`),
  KEY `SOIF_CURRENCY` (`ORIG_CURRENCY_DIM_ID`),
  KEY `SOIF_PRODUCT` (`PRODUCT_DIM_ID`),
  KEY `SLS_ORR_ITM_FCT_TP` (`LAST_UPDATED_TX_STAMP`),
  KEY `SLS_ORR_ITM_FCT_TS` (`CREATED_TX_STAMP`),
  CONSTRAINT `SOIF_CURRENCY` FOREIGN KEY (`ORIG_CURRENCY_DIM_ID`) REFERENCES `currency_dimension` (`DIMENSION_ID`),
  CONSTRAINT `SOIF_ORDERDATE` FOREIGN KEY (`ORDER_DATE_DIM_ID`) REFERENCES `date_dimension` (`DIMENSION_ID`),
  CONSTRAINT `SOIF_PRODUCT` FOREIGN KEY (`PRODUCT_DIM_ID`) REFERENCES `product_dimension` (`DIMENSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `sales_order_item_fact` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
